CREATE TABLE IF NOT EXISTS PUBLIC.users (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING NOT NULL,
	LOGIN CHARACTER VARYING NOT NULL,
	NAME CHARACTER VARYING NOT NULL,
	BIRTHDAY DATE,
	CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	IS_CONFIRMED BOOLEAN NOT NULL,
	CONSTRAINT FRIENDS_USERS_FK_USER FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE,
	CONSTRAINT FRIENDS_USERS_FK_FRIEND FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PUBLIC.AGE_RATING (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	RATING CHARACTER VARYING NOT NULL,
	CONSTRAINT AGE_RATING_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING NOT NULL,
	DESCRIPTION CHARACTER VARYING(200),
	RELEASE_DATE DATE,
	DURATION INTEGER,
	AGE_RATING INTEGER,
	CONSTRAINT FILMS_PK PRIMARY KEY (ID),
	CONSTRAINT FILMS_AGE_RATING_FK FOREIGN KEY (AGE_RATING) REFERENCES PUBLIC.AGE_RATING(ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.CATEGORY (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CATEGORY_NAME CHARACTER VARYING NOT NULL,
	CONSTRAINT CATEGORY_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS_CATEGORY (
	FILM_ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER NOT NULL,
	CONSTRAINT FILMS_CATEGORY_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE CASCADE,
	CONSTRAINT FILMS_CATEGORY_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES PUBLIC.CATEGORY(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS_LIKES (
	FILM_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	CONSTRAINT FILMS_LIKES_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE CASCADE,
	CONSTRAINT FILMS_LIKES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE
);

