INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Комедия');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Драма');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Мультфильм');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Триллер');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Документальный');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Боевик');

INSERT INTO AGE_RATING(RATING) VALUES ('G');
INSERT INTO AGE_RATING(RATING) VALUES ('PG');
INSERT INTO AGE_RATING(RATING) VALUES ('PG-13');
INSERT INTO AGE_RATING(RATING) VALUES ('R');
INSERT INTO AGE_RATING(RATING) VALUES ('NC-17');

INSERT INTO FILMS(NAME, DESCRIPTION, RELEASE_DATE, DURATION, AGE_RATING)
VALUES ('film1', 'description', '2002-12-31', '2:13:13', 1);
INSERT INTO FILMS(NAME, DESCRIPTION, RELEASE_DATE, DURATION, AGE_RATING)
VALUES ('film2', 'description', '2002-1-3', '1:45:19', 3);
INSERT INTO FILMS(NAME, DESCRIPTION, RELEASE_DATE, DURATION, AGE_RATING)
VALUES ('film3', 'description', '1965-4-13', '0:13:53', 5);

INSERT INTO USERS(EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('user1@mail.ru', 'user1', 'user1', '2002-12-6');
INSERT INTO USERS(EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('user2@mail.ru', 'user2', 'user2', '2003-7-27');
INSERT INTO USERS(EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES ('user3@mail.ru', 'user3', 'user3', '2008-9-16');

INSERT INTO FRIENDS(USER_ID, FRIEND_ID, IS_CONFIRMED) VALUES(1, 2, TRUE);
INSERT INTO FRIENDS(USER_ID, FRIEND_ID, IS_CONFIRMED) VALUES(2, 1, TRUE);
INSERT INTO FRIENDS(USER_ID, FRIEND_ID, IS_CONFIRMED) VALUES(3, 1, FALSE);
INSERT INTO FRIENDS(USER_ID, FRIEND_ID, IS_CONFIRMED) VALUES(3, 2, FALSE);

INSERT INTO FILMS_CATEGORY(FILM_ID, CATEGORY_ID) VALUES(1, 2);
INSERT INTO FILMS_CATEGORY(FILM_ID, CATEGORY_ID) VALUES(1, 3);
INSERT INTO FILMS_CATEGORY(FILM_ID, CATEGORY_ID) VALUES(2, 1);
INSERT INTO FILMS_CATEGORY(FILM_ID, CATEGORY_ID) VALUES(2, 2);
INSERT INTO FILMS_CATEGORY(FILM_ID, CATEGORY_ID) VALUES(3, 4);

INSERT INTO FILMS_LIKES(FILM_ID, USER_ID) VALUES(1, 3);
INSERT INTO FILMS_LIKES(FILM_ID, USER_ID) VALUES(2, 1);
INSERT INTO FILMS_LIKES(FILM_ID, USER_ID) VALUES(2, 2);
INSERT INTO FILMS_LIKES(FILM_ID, USER_ID) VALUES(2, 3);
INSERT INTO FILMS_LIKES(FILM_ID, USER_ID) VALUES(3, 2);
INSERT INTO FILMS_LIKES(FILM_ID, USER_ID) VALUES(3, 3);